insta/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path
from django.conf.urls import include
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('users.urls')),
    path('posts/', include('posts.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

posts/urls.py
from django.urls import path
from . import views
app_name = 'posts'

urlpatterns = [
    #  # /posts/
    path('', views.index, name='index'),

# 포스트 기능

    # /posts/create/
    path('create/', views.post_create, name='post_create'),

    # /posts/1/post_delete/
    path('<int:post_id>/post_delete/', views.post_delete, name='post_delete'),

    # /posts/1/post_update/
    path('<int:post_id>/post_update/', views.post_update, name='post_update'),

    #/posts/1/post_like/
    path('<int:post_id>/post_like/', views.post_like, name='post_like'),
    
    # /posts/search/
    path('search/', views.search, name='post_search'),

# 댓글 기능

    # /posts/1/comment_create/
    path('<int:post_id>/comment_create/', views.comment_create, name='comment_create'),
    
    # /posts/1/comment_delete/
    path('<int:comment_id>/comment_delete/',
         views.comment_delete, name='comment_delete'),

    # /posts/1/comment_update/
    path('<int:comment_id>/comment_update/',
         views.comment_update, name='comment_update'),
]

posts/models.py
from django.db import models
from users import models as user_model
# Create your models here.
class TimeStamedModel(models.Model):
    create_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        abstract = True

class Post(TimeStamedModel):
    author = models.ForeignKey(
            user_model.User,
            null=True,
            on_delete=models.CASCADE,
            related_name="post_author"
        )
    image = models.ImageField(blank=True)
    caption = models.TextField(blank=True) # blank=False로 할 경우 무조건 받아야함
    image_likes = models.ManyToManyField(
                    user_model.User,
                    blank=True, 
                    related_name="post_image_likes")

    def __str__(self):
        return f"{self.author} : {self.caption}"

class Comments(TimeStamedModel):
    author = models.ForeignKey(
            user_model.User,
            null=True,
            on_delete=models.CASCADE,
            related_name="comment_author"          
        )
    posts = models.ForeignKey(
            Post,
            null=True,
            on_delete=models.CASCADE,
            related_name="comment_post"
        )
    contents = models.TextField(blank=True)

    def __str__(self):
        return f"{self.author} : {self.contents}"

posts/forms.py
from django import forms
from .models import Post, Comments

class CreatePostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ["caption", "image"]

        labels = {
            "caption" : "내용",
            "image" : "사진",
        }


class UpdatePostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ["caption"]

        labels = {
            "caption": "내용"
        }


class CommentForm(forms.ModelForm):
    contents = forms.CharField(widget=forms.Textarea, label="")
    class Meta:
        model = Comments
        fields = ["contents"]
        
        labels = {
            "contents":"내용"
        }

posts/views.py
from urllib import response
from django.db.models import Q
from django.shortcuts import render, get_object_or_404, redirect
from django.urls import reverse
from django.contrib import messages
from datetime import datetime
from django.core.paginator import Paginator
from django.http import JsonResponse

from .forms import CreatePostForm, CommentForm, UpdatePostForm
from users.models import User as user_model
from . import models, serializers
# Create your views here.

def index(request):
    if request.method == 'GET':

        if request.user.is_authenticated:
            comment_form = CommentForm()

            user = get_object_or_404(user_model, pk=request.user.id)
            following = user.following.all()
            posts = models.Post.objects.filter(
                Q(author__in=following) | Q(author=user) #following된 유저 포스트를 가져온다.
            ).order_by('-create_at') # .order_by('-created_at') -> 작성일시 순으로 정렬 "-"를 써줌으로 내림차순

            serializer = serializers.PostSerializer(posts, many=True)
            # print(serializer.data)

            return render(
                request, 
                'posts/main.html', {'posts': serializer.data, 'comment_form': comment_form})

# 포스트 작성 기능
def post_create(request):
    if request.method == 'GET':
        form = CreatePostForm()
        return render(request, 'posts/post_create.html', {'form' : form})

    elif request.method == 'POST':
        if request.user.is_authenticated:
            user = get_object_or_404(user_model, pk=request.user.id)
            # image = request.FILES['image']
            # caption = request.POST['caption']

            # new_post = models.Post.objects.create(
            #     author = user,
            #     image = image,
            #     caption = caption
            #     )
            # new_post.save()

            form = CreatePostForm(request.POST, request.FILES)
            if form.is_valid():
                post = form.save(commit=False)
                post.author = user
                post.save()
            else :
                print(form.errors)

            return redirect(reverse('posts:index'))

        else :
            return render(request, "index.html")

# 포스트 삭제 기능
def post_delete(request, post_id):
    if request.user.is_authenticated:
        post = get_object_or_404(models.Post, pk=post_id)
        if request.user == post.author:
            post.delete()
        
        return redirect(reverse('posts:index'))
    
    else :
        return render(request, 'users/main.html')

# 포스트 수정 기능

def post_update(request, post_id):

    if request.user.is_authenticated:
        post = get_object_or_404(models.Post, pk=post_id)
        if request.user != post.author:
            messages.error('수정권한이 없습니다.')
            return redirect(reverse('post:index'))

        if request.method == 'GET':
            form = UpdatePostForm(instance=post)
            return render(
                request,
                'posts/post_update.html',
                {'form': form, 'post': post}
                )

        elif request.method == 'POST':
            form = UpdatePostForm(request.POST)
            if form.is_valid():
                post.caption = form.cleaned_data['caption']
                post.save()

            return redirect(reverse('posts:index'))

    else:
        return render(request, "posts/main.html")

# 포스트 좋아요 기능

def post_like(request, post_id):
    response_body = {"result" : ""}
    
    if request.user.is_authenticated:
        if request.method == "POST":

            post = get_object_or_404(models.Post, pk=post_id)
            existed_user = post.image_likes.filter(pk=request.user.id).exists() # image_likes가 있다면 True 없으면 False
            if existed_user:
                # 좋아요 누른 상태일 경우 취소
                post.image_likes.remove(request.user)
                response_body["result"] = "dislike"
                # 좋아요가 아닐 경우 좋아요 표시
            else :
                post.image_likes.add(request.user)
                response_body["result"] = "like"

            return JsonResponse(status=200, data=response_body) # http 상태표 200
    else :
        return JsonResponse(status=403, data=response_body) # http 상태표 403

# 포스트 찾기 기능
def search(request):
    if request.user.is_authenticated:
        if request.method == 'GET':
            searchKeyword = request.GET.get("q","")
            comment_form = CommentForm()

            user = get_object_or_404(user_model, pk=request.user.id)
            following = user.following.all()
            posts = models.Post.objects.filter(
                # following된 유저 포스트를 가져온다.
                (Q(author__in=following) | Q(author=user)) & Q(caption__contains=searchKeyword)
            ).order_by('-create_at')
             # .order_by('-created_at') -> 작성일시 순으로 정렬 "-"를 써줌으로 내림차순

            serializer = serializers.PostSerializer(posts, many=True)
            # print(serializer.data)

            return render(
                request,
                'posts/main.html', {'posts': serializer.data, 'comment_form': comment_form})

    else:
        return render(request, 'users/main.html')

# 댓글 작성 기능
def comment_create(request, post_id):
    if request.user.is_authenticated:
        post = get_object_or_404(models.Post, pk=post_id)

        form = CommentForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.author = request.user
            comment.posts = post
            comment.save()

            return redirect(reverse("posts:index") + "#comment-" + str(comment.id))

        else:
            return render(request, "{% url 'users:login' %}")

# 댓글 삭제 기능
def comment_delete(request, comment_id):
    if request.user.is_authenticated:
        comment = get_object_or_404(models.Comments, pk=comment_id)
        if request.user == comment.author:
            comment.delete()

        return redirect(reverse('posts:index'))

    else:
        return render(request, 'users/main.html')

# 댓글 수정 기능
def comment_update(request, comment_id):
    if request.user.is_authenticated:
        comment = get_object_or_404(models.Comments, pk=comment_id)
        if request.user != comment.author:
            messages.error('수정권한이 없습니다.')
            return redirect(reverse('post:index'))

        if request.method == 'POST':
            form = CommentForm(request.POST)
            if form.is_valid():
                comment.contents = form.cleaned_data['contents']
                comment.save()

            return redirect(reverse('posts:index'))
        else :
            form = CommentForm(instance=comment)
        context = {'form': form, 'comment': comment}
        return render(request, 'posts/comment_update.html', context)
    else:
        return render(request, "posts/main.html")

templates/posts/base.html
{% load static %}
<html lang="kr">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" type="text/css" href="{% static 'posts/css/base.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'posts/css/header.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'posts/css/main.css' %}">

    <!-- Font Awesome -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <title>포스트</title>
</head>
<body>
    <div class="header">
        {% include "posts/header.html" %}
    </div>
    {% block content %}
    {% endblock content %}
    <script type="text/javascript" src="{% static 'posts/js/posts.js' %}"></script>
</body>
</html>

templates/posts/comment_update.html
{% extends 'posts/base.html' %}
{% block content %}

<div class="comment-create">
    <div>
        update page
    </div>
    <div class="form">
        <form action="{% url 'posts:comment_update' comment.id %}" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form.as_p }}
            <input type="submit" value="Update">
        </form>
    </div>
</div>

{% endblock %}

templates/posts/header.html
{% load static %}
<header>
    <div class="header-box">
        <div class="main-img">
            <a href="{% url 'posts:index' %}">
                <img src="{% static 'posts/images/main_logo.png'%}" alt="logo">
            </a>
        </div>
        <div class="search">
            <form action="{% url 'posts:post_search' %}" method="GET">
                <input type="text" name="q" placeholder="search">
            </form>
        </div>
        <div class="header-right">
            <div>
                <a href="{% url 'posts:post_create' %}">
                    <i class="fa fa-plus-circle fa-2x"></i>
                </a>
            </div>
            <div>
                <a href="#">
                    <i class="fa fa-user fa-2x"></i>
                </a>
            </div>
        </div>
    </div>
</header>

templates/posts/index.html
{% extends 'posts/base.html' %}
{% block title %}
<title>post</title>
{% endblock %}

{% block navbar %}
{% include 'posts/header.html' %}
{% endblock %}

{% block content %}
<h1>test</h1>
{% endblock %}

templates/posts/main.html
{% extends 'posts/base.html' %}
{% load static  %}
{% block content %}

{% for post in posts %}
    <div class="post-box">
        <!-- header -->
        <div class="header">
            <div class="profile">
                {% if post.author.profile_photo != None %}
                    <img src="{{ post.author.profile_photo }}">
                {% else %}
                    <img src="{% static 'posts/images/no_avatar.png' %}">
                {% endif %}
                <div>
                    {{ post.author.username }}
                </div>
            </div>

            <div class="icon">
                {% if user.id == post.author.id %}
                <a href="{% url 'posts:post_update' post.id %}">
                    <i class="fa fa-pencil fa1x"></i>
                </a>
                <a href="{% url 'posts:post_delete' post.id %}">
                    <i class="fa fa-trash-o fa1x"></i>
                {% endif %}
                </a>
            </div>

        </div>
        
        <!-- image -->
        <img class="post-image" src="{{ post.image }}">
        
        <!-- image-button -->
        <button id="like-button-{{ post.id }}" onclick="handleLikeClick(this.id)">
        {% if user.id in post.image_likes %}
            <i class="fa fa-heart fa-2x"></i>
        {% else %}
            <i class="fa fa-heart-o fa-2x"></i>
        {% endif %}
        </button>
    
        <div class="desc-box">
            <!-- image-description -->
            <div class="image-desc">
                <b> {{ post.author.username }}</b>
                {{ post.caption }}
            </div>

            <!-- comment -->
            <div class="comment">
                {% for comment in post.comment_post %}
                    <div id="comment-{{ comment.id }}">
                        <b>{{ comment.author.username }}</b>
                        {{ comment.contents }}
                        {% if user.id == comment.author.id %}
                        <a href="{% url 'posts:comment_update' comment.id %}">수정</a>
                        <a href="{% url 'posts:comment_delete' comment.id %}"> 
                            <i class="fa fa-trash-o fa1x"></i>
                        {% endif %}
                        </a>
                    </div>
                {% endfor %}
            </div>
        </div>

        <!-- comment input -->
        <div class="comment-input">
            <form action="{% url 'posts:comment_create' post.id %}" method="POST">
                {% csrf_token %}
                {{ comment_form }}
                <input type="submit" value="Post">
            </form>
        </div>

    </div>

{% endfor %}

{% endblock content %}

templates/posts/navbar.html
{% extends 'base.html' %}
{% block title %}
<title>post</title>
{% endblock %}

{% block content %}
<!-- 네비게이션바 -->

{% endblock %}

templates/posts/post_create.html
{% extends 'posts/base.html' %}
{% block content %}

<div class="post-create">
    <div>
        create page
    </div>
    <div class="form">
        <form action="{% url 'posts:post_create' %}"
                method="post"
                enctype="multipart/form-data">
            {% csrf_token %}
            {{ form.as_p }}
            <input type="submit" value="Create">
        </form>
    </div>
</div>

{% endblock %}

templates/posts/post_update.html
{% extends 'posts/base.html' %}
{% block content %}

<div class="post-create">
    <div>
        update page
    </div>
    <div class="form">
        <form action="{% url 'posts:post_update' post.id %}" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form.as_p }}
            <input type="submit" value="Update">
        </form>
    </div>
</div>

{% endblock %}