insta/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path
from django.conf.urls import include
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('users.urls')),
    path('posts/', include('posts.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from django.conf.urls import url, include
from . import views

app_name = 'users'

urlpatterns = [
    path('', views.index, name='base'),
    path('signup/', views.signup, name='signup'),
    path('log/', views.login_views, name='log'),
    path('logout/', views.logout_views, name='logout'),
]

templates/base.html
{% load static %}

<html lang="ko">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!--===============================================================================================-->
    <link rel="icon" type="image/png" href="{% static 'assets/images/icons/favicon.ico' %}">
    <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="{% static 'assets/vendor/bootstrap/css/bootstrap.min.css' %}">
    <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css"
        href="{% static 'assets/fonts/font-awesome-4.7.0/css/font-awesome.min.css' %}">
    <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="{% static 'assets/vendor/animate/animate.css' %}">
    <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="{% static 'assets/vendor/css-hamburgers/hamburgers.min.css' %}">
    <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="{% static 'assets/vendor/select2/select2.min.css' %}">
    <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="{% static 'assets/css/util.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'assets/css/main.css' %}">
    <!--===============================================================================================-->
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" type="text/css" href="{% static 'bootstrap.min.css' %}">
    <!-- pybo css -->
    <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">

    {% block title %}
    <title>hello</title>
    {% endblock %}
</head>

<body>
    {% block navbar %}
    {% endblock %}
    <!-- 기본 템플릿 안에 삽입될 내용 start -->
    {% block content %}
    {% endblock %}
    <!-- 기본 템플릿 안에 삽입될 내용 end -->

    <!-- jquery js -->
    <script src="{% static 'jquery-3.6.0.min.js' %}"></script>
    <!-- bootstrap js -->
    <script src="{% static 'bootstrap.min.js' %}"></script>
    <!-- 자바스크립트 start -->
    {% block script %}
    {% endblock %}
    <!-- 자바스크립트 end -->
</body>

</html>

templates/index.html
{%extends 'base.html' %}
{% load static %}

{% block content %}
<h2>환영합니다.</h2>
<h3><a href="{% url 'users:log' %}">로그인</a></h3>
{% endblock %}

templates/login.html
{% extends 'index.html' %}
{% load static %}
{% block title %}
<title>login_page</title>
{% endblock %}

{% block content %}
    <!-- 회원가입 창 -->
    <!-- ======= Hero Section ======= -->
    <section id="hero" class="d-flex align-items-center">

        <div class="limiter">
            <div class="container-login100">
                <div class="wrap-login100">
                    <div class="login100-pic js-tilt" data-tilt>
                        <img src="{% static 'assets/images/img-01.png' %}" alt="IMG">
                    </div>

                    <form class="login100-form validate-form" method="POST">
                        {% csrf_token %}
                        <span class="login100-form-title">
                            로그인하기
                        </span>

                        <div class="wrap-input100 validate-input" data-validate="아이디를 입력해주세요">
                            <input class="input100" type="text" name="username" placeholder="username">
                            <span class="focus-input100"></span>
                            <span class="symbol-input100">
                                <i class="fa fa-envelope" aria-hidden="true"></i>
                            </span>
                        </div>

                        <div class="wrap-input100 validate-input" data-validate="비밀번호를 입력해주세요">
                            <input class="input100" type="password" name="password" placeholder="Password">
                            <span class="focus-input100"></span>
                            <span class="symbol-input100">
                                <i class="fa fa-lock" aria-hidden="true"></i>
                            </span>
                        </div>

                        <div class="container-login100-form-btn">
                            <button class="login100-form-btn">
                                Login
                            </button>
                        </div>

                        <div class="text-center p-t-12">
                            <span class="txt1">
                                Forgot
                            </span>
                            <a class="txt2" href="#">
                                Username / Password?
                            </a>
                        </div>

                        <div class="text-center p-t-136">
                            <a class="txt2" href="{% url 'users:signup' %}">
                                회원가입
                                <i class="fa fa-long-arrow-right m-l-5" aria-hidden="true"></i>
                            </a>
                        </div>
                    </form>
                </div>
            </div>
        </div>




        <!--===============================================================================================-->
        <script src="{% static 'assets/vendor/jquery/jquery-3.2.1.min.js' %}"></script>
        <!--===============================================================================================-->
        <script src="{% static 'assets/vendor/bootstrap/js/popper.js' %}"></script>
        <script src="{% static 'assets/vendor/bootstrap/js/bootstrap.min.js' %}"></script>
        <!--===============================================================================================-->
        <script src="{% static 'assets/vendor/select2/select2.min.js' %}"></script>
        <!--===============================================================================================-->
        <script src="{% static 'assets/vendor/tilt/tilt.jquery.min.js' %}"></script>
        <script>
            $('.js-tilt').tilt({
                scale: 1.1
            })
        </script>
        <!--===============================================================================================-->
        <script src="{% static 'assets/js/main.js' %}"></script>
    </section><!-- End Hero -->

    <main id="main">

    </main><!-- End #main -->

{% endblock %}